### ISSUE TITLE
CONTRUCCIÓN DE SUMIDEROS

### ISSUE THREAD

**Issue by esantos2100** [esantos2100/CONSTRUCCION-Y-REGENERACION-URBANA-DEL-CALLEJON-26-B2#7]
CONSTRUCCIÓN DE SUMIDEROS Y SE VERIFICA EL CUMPLIMIENTO Y AVANCE DE OBRA EN ESTE PROCESO

**Comment by Edgar400901** [comment]
Implementación de sumideros previa verificación de cumplimiento

**Comment by Edgar400901** [comment]
EXCAVACION EN TIERRA A MANO PARA ASIENTO DE FUNDACIONES,ZANJAS, ETC.

**Comment by Edgar400901** [comment]
CARGA A MANO DE MATERIAL PROVENIENTE DE LAS EXCAVACIONES

**Comment by Edgar400901** [comment]
CONSTRUCCION DE BASE DE PIEDRA PICADA CORRESPONDIENTE AOBRAS PREPARATIVAS

**Comment by Edgar400901** [comment]
EJECUCIÓN DE LA OBRA 



![3](https://user-images.githubusercontent.com/75945565/102625604-b6ae6a80-4113-11eb-951d-933a2a2392b7.jpg)
