### ISSUE TITLE
CULMINACIÓN DE SISTEMAS DE SOTERRADOS

### ISSUE THREAD

**Issue by esantos2100** [esantos2100/CONSTRUCCION-Y-REGENERACION-URBANA-DEL-CALLEJON-26-B2#8]
CULMINACIÓN DE LA FASE DE SOTERRAMIENTO DE LOS SISTEMAS IMPLÍCITOS EN LA RECONSTRUCCIÓN DE LA VÍA.

**Comment by Edgar400901** [comment]
Revisión términos de referencia

**Comment by Edgar400901** [comment]
Culminación del sistema 

> ![1](https://user-images.githubusercontent.com/75945565/102624143-9da4ba00-4111-11eb-89d0-982bf6c54e65.jpg)
